version: '3.9'
services:
  stores_backend:
    container_name: stores_backend
    restart: always
    build: .
    ports:
      - 8002:8002
    networks: 
      - case1_demo
    volumes:
      - .:/app
    depends_on:
      - cassandradb
      - servstoresdb

  cassandradb:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    environment:
      CASSANDRA_USERNAME: yourusername
      CASSANDRA_PASSWORD: yourpassword
    ports:
      - 9042:9042
    volumes:
      - cassandra-data:/var/lib/cassandra/data
    networks:
      - case1_demo

  servstoresdb:
    image: mongo:latest
    restart: always
    container_name: container_servicestores
    environment:
      - MONGO_INITDB_ROOT_USERNAME=servicestores
      - MONGO_INITDB_ROOT_PASSWORD=servicestores
    volumes:
      - ./mongodb:/db/servicestores
    ports:
      - "27017:27017"
    networks: 
      - case1_demo

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    networks: 
      - case1_demo
    environment:
      - ME_CONFIG_MONGODB_SERVER=servstoresdb
      - ME_CONFIG_BASICAUTH_USERNAME=servicestores
      - ME_CONFIG_BASICAUTH_PASSWORD=servicestores
      # - ME_CONFIG_MONGODB_AUTH_DATABASE=servicestores
      - ME_CONFIG_MONGODB_ADMINUSERNAME=servicestores
      - ME_CONFIG_MONGODB_ADMINPASSWORD=servicestores
      - ME_CONFIG_MONGODB_URL=mongodb://servicestores:servicestores@servstoresdb:27017/ 
    depends_on:
      - servstoresdb

volumes:
  cassandra-data:
  mongodb_data_volume:

networks:
  case1_demo:
    name: net-case1-demo





